### ISSUE TITLE
Initial website info

### ISSUE THREAD

**Issue by doobilydo** [mkemesh/mkemesh.org#1]
- [x] Our name (mkemesh), the logo
- [x] A mission statement (our goals)
- [x] The bylaws
- [x] Contact info (info@mkemesh.org)
- [x] A calendar with meeting dates (a google calendar embed?)
- [x] FAQs
- [x] Fundraising/donations

**Comment by BeamBrain** [comment]
Anchorage DSA has a calendar embed: https://www.anchoragedsa.org/calendar.html

We could reach out to them and ask how they set it up.

**Comment by doobilydo** [comment]
Google calendar, definitely. Evan wanted to do that. We need to reach out to whomever has access to the mke mesh google account (assuming we have one), then create a calendar, and get the embed link for the public calendar. There _may_ be API hurdles to jump through.

I do not know who's is control of that google account (if anyone).

**Comment by doobilydo** [comment]
trying this: https://fullcalendar.io/

**Comment by BeamBrain** [comment]
I could take a crack at adding the calendar tomorrow.

**Comment by doobilydo** [comment]
Calendar setup! List of things to include on it here: https://github.com/mkemesh/mkemesh.org/issues/7
