### ISSUE TITLE
Contact Form Testing

### ISSUE THREAD

**Issue by doobilydo** [mkemesh/mkemesh.org#4]
Just need to make sure it works. Do we have a testing environment?

**Comment by rocksynthetic** [comment]
Hey sorry I missed this; I'm not getting emails or anything when issues are opened; I should change that...

Anyway, I observed that the form successfully sent an email. Could use some sort of user feedback acknowledging that the send was successful though.

**Comment by doobilydo** [comment]
Great to hear! (I just had to update my notifications as well)

Let's try starting with just a pop-up dialog:

>Thank you, [user's name]!
> Watch your email (and spam) for: [mkemesh email]

Then clear the contact fields?
